### ISSUE TITLE
Error on missing key 

### ISSUE THREAD

**Issue by bacosmin** [mose/rails-i18nterface#1]
The issue is on config/initializers/rails_i18nterface/missing_translation.rb line 5 

The blank validation from active record sends to i18n symbol key instead of string and key.split is crashing

Suggested fix: 
 use key.to_s.split

**Comment by mose** [comment]
Good catch, I will release a new version with your fix. Thanks! :+1:

**Comment by bacosmin** [comment]
You are welcome
