### ISSUE TITLE
Error on save 

### ISSUE THREAD

**Issue by bacosmin** [mose/rails-i18nterface#2]
I18n::InvalidLocaleData - can not load translations from ...yml: #<TypeError: allocator undefined for Proc>:

If you load rails_i18n and dont require the pluralization it throws the error from above

**Comment by mose** [comment]
Can you provide some more contextual information ? What configuration setting leads to this error ? using which version of rails and rails_i18n ? So then I can reproduce it and try to find a fix.

**Comment by mutil** [comment]
I can reproduce this with these steps:
- `rails new testapp`
- add gems `rails-i18n` and `rails-i18nterface`
- insert the mount line in routes.rb
- navigate to /translate
- press `Save Translations`.

Requiring pluralization, as OP mentions, doesn't make any difference for me.

Tested with rails-4.2.6 & rails-i18n-4.0.8.

**Comment by mose** [comment]
Thanks for that detailled report. I found the problem, rails_18n adds a Proc in the translation for pluralization method and psych can write a proc object in yaml, but has no idea how to read it (!?). I'm gonna fix that asap.
